### ISSUE TITLE
[Bug]: Application only accessible via localhost, access via local IP causes errors

### ISSUE THREAD

**Issue by thatnerdjack** [Shelf-nu/shelf.nu#1519]
### Contact Details

dohertyjackw@gmail.com

### What happened?

Steps to reproduce:

1. Install release 1.12.5
2. Fill out env file, run `npm install`, `npx remix init`, `npm run setup`, `npm run build`, `npm run start`.
3. Access site via IP address or proxy (e.g. http://192.168.x.x:3000 or https://x.y.ts.net, not localhost:3000)
4. Signup with an account (works as expected)
5. Login, where flow sends you to domain.tld/assets, and see error
6. Access via localhost:3000 and loging works as expected, brining me to the assets page.

Tried installing a certificate in vite.config.ts following the remix instrucitns, but app is still not serving https and does not solve the issue (proxy via tailscale serve also does not work, if that is helpful information).

### What is the expected behaviour?

Be presented with the assets page and application.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
In browser error:
TypeError: Cannot read properties of undefined (reading 'title')
    at Module.Fn (http://100.122.54.50:3000/file-assets/n70mwbvk/assets._index-B8cTTNAv.js:6:2852)
    at j1 (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:194:7108)
    at Fu (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:38:19518)
    at Sh (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:43918)
    at yh (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:39690)
    at Kv (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:39618)
    at Ki (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:39472)
    at Ya (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:35851)
    at ph (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:40:34802)
    at P (http://100.122.54.50:3000/file-assets/n70mwbvk/components-BTdeEibX.js:25:1569)

Browser console:
TypeError: Cannot read properties of undefined (reading 'title')
    at Module.Fn (assets._index-B8cTTNAv.js:6:2852)
    at j1 (components-BTdeEibX.js:194:7108)
    at Fu (components-BTdeEibX.js:38:19518)
    at Sh (components-BTdeEibX.js:40:43918)
    at yh (components-BTdeEibX.js:40:39690)
    at Qv (components-BTdeEibX.js:40:39662)
    at ph (components-BTdeEibX.js:40:34665)
    at P (components-BTdeEibX.js:25:1569)
    at MessagePort.G (components-BTdeEibX.js:25:1937)
overrideMethod @ hook.js:608
sp @ components-BTdeEibX.js:156
Fu @ components-BTdeEibX.js:38
Sh @ components-BTdeEibX.js:40
yh @ components-BTdeEibX.js:40
Qv @ components-BTdeEibX.js:40
ph @ components-BTdeEibX.js:40
P @ components-BTdeEibX.js:25
G @ components-BTdeEibX.js:25
components-BTdeEibX.js:156 

TypeError: Cannot read properties of undefined (reading 'title')
    at Module.Fn (assets._index-B8cTTNAv.js:6:2852)
    at j1 (components-BTdeEibX.js:194:7108)
    at Fu (components-BTdeEibX.js:38:19518)
    at Sh (components-BTdeEibX.js:40:43918)
    at yh (components-BTdeEibX.js:40:39690)
    at Kv (components-BTdeEibX.js:40:39618)
    at Ki (components-BTdeEibX.js:40:39472)
    at Ya (components-BTdeEibX.js:40:35851)
    at ph (components-BTdeEibX.js:40:34802)
    at P (components-BTdeEibX.js:25:1569)
overrideMethod @ hook.js:608
sp @ components-BTdeEibX.js:156
Fu @ components-BTdeEibX.js:38
Sh @ components-BTdeEibX.js:40
yh @ components-BTdeEibX.js:40
Kv @ components-BTdeEibX.js:40
Ki @ components-BTdeEibX.js:40
Ya @ components-BTdeEibX.js:40
ph @ components-BTdeEibX.js:40
P @ components-BTdeEibX.js:25
G @ components-BTdeEibX.js:25
components-BTdeEibX.js:40 

TypeError: Cannot read properties of undefined (reading 'title')
    at Module.Fn (assets._index-B8cTTNAv.js:6:2852)
    at j1 (components-BTdeEibX.js:194:7108)
    at Fu (components-BTdeEibX.js:38:19518)
    at Sh (components-BTdeEibX.js:40:43918)
    at yh (components-BTdeEibX.js:40:39690)
    at Kv (components-BTdeEibX.js:40:39618)
    at Ki (components-BTdeEibX.js:40:39472)
    at Ya (components-BTdeEibX.js:40:35851)
    at ph (components-BTdeEibX.js:40:34802)
    at P (components-BTdeEibX.js:25:1569)
```

**Comment by thatnerdjack** [comment]
My env file if helpful:

```
# Most of the connection information can be found within the Supabase dashboard. Navigate to your project > Project Settings > Database.
# There you will be able to find the values you need to use below
# You can either copy the connection string and insert your password or use the connection parameters to build the string yourself
DATABASE_URL="postgresql://postgres.***@***.supabase.com:5432/postgres"

# Direct URL is used by prisma to run migrations. Depending on how you run your migrations, you could skip this in your procution environment
# More info here: https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections#external-connection-poolers
# and here: https://www.prisma.io/docs/orm/reference/prisma-schema-reference#fields
DIRECT_URL="postgresql://***@***.supabase.com:5432/postgres"

SUPABASE_ANON_PUBLIC="***"
SUPABASE_SERVICE_ROLE="***"
SUPABASE_URL="https://***.supabase.co"
SESSION_SECRET="***"
SERVER_URL="https://shelf.tail24ef4e.ts.net"

# Used for generating cuid with lowered chance of collision. Optional
# FINGERPRINT="a-custom-host-fingerprint"

SMTP_HOST="***"
SMTP_USER="***"
SMTP_PWD="***"
SMTP_FROM="\"Shelf@Team5924\" <***>"

# Set this to false to disable requirement of subscription for premium features. This will make premium features available for all users
# You can also directly adjust this in remix.config.js and set it to false
ENABLE_PREMIUM_FEATURES="false"

# The Stripe keys are needed only if you want to enable premium features
# STRIPE_SECRET_KEY="stripe-secret-key"
# STRIPE_PUBLIC_KEY="stripe-public-key"
# STRIPE_WEBHOOK_ENDPOINT_SECRET="stripe-endpoint-secret"

MAPTILER_TOKEN="***"
# MICROSOFT_CLARITY_ID="microsoft-clarity-id"

INVITE_TOKEN_SECRET="***"
# GEOCODE_API_KEY="geocode-api-key"
```

**Comment by thatnerdjack** [comment]
My bad! I pulled down the latest main and this seems to be fixed. I'll close the issue.
