### ISSUE TITLE
[Enhancement]: Cannot use empty SMTP_USER & SMTP_PWD

### ISSUE THREAD

**Issue by jon91** [Shelf-nu/shelf.nu#756]
### What happened?

`ShelfStackError 👀: SMTP_PWD is not set`

### What is the expected behaviour?

Allow empty usage of usr/pw as some SMTP relays are authenticated by IP

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by DonKoko** [comment]
hey @jon91. Thanks for opening an issue in our repository.

Currently thats what we have built and we support. We understand that there are many different ways you can auth but thats the approach we have taken so far.
That being said, I will re-label your issue as its not a bug, but rather an enhancement request.

If you are interested in having auth working in different way, please feel free to open a PR with your suggestion. You can find the contribution guide here: https://github.com/Shelf-nu/shelf.nu/blob/main/CONTRIBUTING.md

Moreover, I will point you to the file where we initiate our transporter used for sending emails: https://github.com/Shelf-nu/shelf.nu/blob/main/app/emails/transporter.server.ts

Please let us know if you have any other questions.

**Comment by DonKoko** [comment]
Closing due to inactivity

**Comment by DonKoko** [comment]
hey @microbearlogist, thank you for your input and keeping the conversation going. 
I am honestly not sure how sending emails works with IP authentication. Do you have something you can share that will give me more context on how your mailing system works. SMTP sending with username/pwd authentication is the most common and standard way of sending emails so this is what we support currently.

**Comment by microbearlogist** [comment]
@DonKoko Yes I tried empty string for SMTP_PWD and SMTP_USER, unfortunaley, shelf refuse to start when SMTP_USER or SMTP_PWD are empty.

```
ShelfError: SMTP_USER is not set
    at getEnv (file:///src/build/server/instrument.server.js:57:11)
    at file:///src/build/server/instrument.server.js:95:17
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  cause: null,
  label: 'Environment',
  title: undefined,
  additionalData: undefined,
  shouldBeCaptured: true,
  status: 500,
  traceId: 'd5l23ghj5xcxrsdhvfpyj35s'
}
```


```
ShelfError: SMTP_PWD is not set
    at getEnv (file:///src/build/server/instrument.server.js:57:11)
    at file:///src/build/server/instrument.server.js:90:16
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  cause: null,
  label: 'Environment',
  title: undefined,
  additionalData: undefined,
  shouldBeCaptured: true,
  status: 500,
  traceId: 'eqbmkoswgwcexh1posoagmas'
}
```

**Comment by DonKoko** [comment]
hey @microbearlogist ,
I have made an update to shelf that should now allow for empty strings in those 2 values. Can you pull the latest version on the main branch and try it? I hope this resolves your issue.

**Comment by microbearlogist** [comment]
When credentials are empty, it seems that nodemailer authentification needs to be disabled (by setting auth:false):

https://github.com/nodemailer/nodemailer/issues/1142

**Comment by microbearlogist** [comment]
Hey @DonKoko, It is up to me to thank you for your help and your time.

Your latest update solves the problem, everything works perfectly!
