### ISSUE TITLE
[Bug]: invalid type on SESSION_SECRET deploying with docker

### ISSUE THREAD

**Issue by whoamiafterall** [Shelf-nu/shelf.nu#839]
### Contact Details

schmusi@systemli.org

### What happened?

Steps to reproduce:

1. Go to ghcr.io/shelf-nu/shelf.nu:latest
2. Pull the image using docker pull
3. Run a Container with -e 'SESSION_SECRET={anything}'
4. See error:

> NODE_ENV=production node build/index.js

/myapp/node_modules/zod/lib/types.js:143
        throw result.error;
        ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "SESSION_SECRET"
    ],
    "message": "Required"
  }
]
    at get error [as error] (/myapp/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/myapp/node_modules/zod/lib/types.js:143:22)
    at Object.<anonymous> (/myapp/build/index.js:18771:69)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'SESSION_SECRET' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'undefined',
      path: [ 'SESSION_SECRET' ],
      message: 'Required'
    }
  ]
}

Node.js v20.11.1

### What is the expected behaviour?

I would expect it to take in the supabase Session_Secret as a string.
I used different real secrets and some words like "test", but it always gave me the same invalid_type error.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox

**Comment by whoamiafterall** [comment]
Hey @anatolinicolae - if you find some time to look into this, i would be really grateful! Thanks :)

**Comment by anatolinicolae** [comment]
@whoamiafterall can you provide a `docker run` example that leads to that error? ([something like this](https://github.com/Shelf-nu/shelf.nu/pull/644#issuecomment-1883453447) that I can run against my test db)

I feel like that's something wrong with either string length (but you said "test" doesn't work 🤔) or something is not properly escaped...

**Comment by whoamiafterall** [comment]
> @whoamiafterall can you provide a `docker run` example that leads to that error? ([something like this](https://github.com/Shelf-nu/shelf.nu/pull/644#issuecomment-1883453447) that I can run against my test db)

I'm using [udocker](https://github.com/indigo-dc/udocker/) because i dont't have root access to the server. I'm pretty sure that's not the root cause of the error though.
The commands i'm using are these:
udocker pull ghcr.io/shelf-nu/shelf.nu:main-9b656b6 
udocker create --name=shelf ghcr.io/shelf-nu/shelf.nu:main-9b656b6 
udocker run shelf --env-file=~/.env-file --publish=3000:8080

I don't think i should post my whole .env-file here, but the Secret causing the problem is this one:
SESSION_SECRET=7C7qiQ+4TjB4gkBk2sBx10GwUyYzMOd0pIyi4rCGezqr9uyQrsOVpNVaqtc+5RoTbYsn0N8CY81u538cWM80pw==

I also tried with another one (randomly generated by supabase). I also tried "test".

> I feel like that's something wrong with either string length (but you said "test" doesn't work 🤔) or something is not properly escaped...

That seems like a possible answer, yes.

**Comment by whoamiafterall** [comment]
> You can also work on some further debugging on your side. Run the following command after your `docker create` or `docker run`, and make sure container env vars match the ones you defined:
> 
> ```shell
> docker inspect shelf-container-name -f "{{range .Config.Env}}{{println .}}{{end}}"
> ```

I think udocker works a bit different in that matter, there seem to be no ENV Vars in here:
```

{
    "architecture": "amd64",
    "config": {
        "Entrypoint": [
            "./start.sh"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NODE_VERSION=20.11.1",
            "YARN_VERSION=1.22.19",
            "NODE_ENV=production",
            "PORT=8080"
        ],
        "Labels": {
            "org.opencontainers.image.created": "2024-03-09T16:32:43.325Z",
            "org.opencontainers.image.description": "shelf is open source Asset Management Infrastructure for absolutely everyone.",
            "org.opencontainers.image.licenses": "AGPL-3.0",
            "org.opencontainers.image.revision": "9b656b6c593a1c4175ae405308c384b8c6f02a3e",
            "org.opencontainers.image.source": "https://github.com/Shelf-nu/shelf.nu",
            "org.opencontainers.image.title": "shelf.nu",
            "org.opencontainers.image.url": "https://github.com/Shelf-nu/shelf.nu",
            "org.opencontainers.image.version": "main-9b656b6"
        },
        "OnBuild": null,
        "WorkingDir": "/myapp"
    },
    "created": "2024-03-09T16:33:39.380748449Z",
    "history": [
        {
            "created": "2024-02-13T00:37:22.220329179Z",
            "created_by": "/bin/sh -c #(nop) ADD file:eb6a3def1f69e76655620640e610015f285bc23c97e89855feb1f0548309d518 in / "
        },
        {
            "created": "2024-02-13T00:37:22.50544929Z",
            "created_by": "/bin/sh -c #(nop)  CMD [\"bash\"]",
            "empty_layer": true
        },
        {
            "created": "2024-02-13T08:11:47.419452112Z",
            "created_by": "/bin/sh -c groupadd --gid 1000 node   && useradd --uid 1000 --gid node --shell /bin/bash --create-home node"
        },
        {
            "created": "2024-02-15T22:55:44.550377913Z",
            "created_by": "/bin/sh -c #(nop)  ENV NODE_VERSION=20.11.1",
            "empty_layer": true
        },
        {
            "created": "2024-02-15T22:56:12.304739274Z",
            "created_by": "/bin/sh -c ARCH= OPENSSL_ARCH= && dpkgArch=\"$(dpkg --print-architecture)\"     && case \"${dpkgArch##*-}\" in       amd64) ARCH='x64' OPENSSL_ARCH='linux-x86_64';;       ppc64el) ARCH='ppc64le' OPENSSL_ARCH='linux-ppc64le';;       s390x) ARCH='s390x' OPENSSL_ARCH='linux*-s390x';;       arm64) ARCH='arm64' OPENSSL_ARCH='linux-aarch64';;       armhf) ARCH='armv7l' OPENSSL_ARCH='linux-armv4';;       i386) ARCH='x86' OPENSSL_ARCH='linux-elf';;       *) echo \"unsupported architecture\"; exit 1 ;;     esac     && set -ex     && apt-get update && apt-get install -y ca-certificates curl wget gnupg dirmngr xz-utils libatomic1 --no-install-recommends     && rm -rf /var/lib/apt/lists/*     && export GNUPGHOME=\"$(mktemp -d)\"     && for key in       4ED778F539E3634C779C87C6D7062848A1AB005C       141F07595B7B3FFE74309A937405533BE57C7D57       74F12602B6F1C4E913FAA37AD3A89613643B6201       DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7       61FC681DFB92A079F1685E77973F295594EC4689       8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600       C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8       890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4       C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C       108F52B48DB57BB0CC439B2997B01419BD92F80A       A363A499291CBBC940DD62E41F10027AF002F8B0     ; do       gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys \"$key\" ||       gpg --batch --keyserver keyserver.ubuntu.com --recv-keys \"$key\" ;     done     && curl -fsSLO --compressed \"https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz\"     && curl -fsSLO --compressed \"https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc\"     && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc     && gpgconf --kill all     && rm -rf \"$GNUPGHOME\"     && grep \" node-v$NODE_VERSION-linux-$ARCH.tar.xz\\$\" SHASUMS256.txt | sha256sum -c -     && tar -xJf \"node-v$NODE_VERSION-linux-$ARCH.tar.xz\" -C /usr/local --strip-components=1 --no-same-owner     && rm \"node-v$NODE_VERSION-linux-$ARCH.tar.xz\" SHASUMS256.txt.asc SHASUMS256.txt     && find /usr/local/include/node/openssl/archs -mindepth 1 -maxdepth 1 ! -name \"$OPENSSL_ARCH\" -exec rm -rf {} \\;     && apt-mark auto '.*' > /dev/null     && find /usr/local -type f -executable -exec ldd '{}' ';'       | awk '/=>/ { so = $(NF-1); if (index(so, \"/usr/local/\") == 1) { next }; gsub(\"^/(usr/)?\", \"\", so); print so }'       | sort -u       | xargs -r dpkg-query --search       | cut -d: -f1       | sort -u       | xargs -r apt-mark manual     && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false     && ln -s /usr/local/bin/node /usr/local/bin/nodejs     && node --version     && npm --version"
        },
        {
            "created": "2024-02-15T22:56:12.802162431Z",
            "created_by": "/bin/sh -c #(nop)  ENV YARN_VERSION=1.22.19",
            "empty_layer": true
        },
        {
            "created": "2024-02-15T22:56:28.337986183Z",
            "created_by": "/bin/sh -c set -ex   && savedAptMark=\"$(apt-mark showmanual)\"   && apt-get update && apt-get install -y ca-certificates curl wget gnupg dirmngr --no-install-recommends   && rm -rf /var/lib/apt/lists/*   && export GNUPGHOME=\"$(mktemp -d)\"   && for key in     6A010C5166006599AA17F08146C2130DFD2497F5   ; do     gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys \"$key\" ||     gpg --batch --keyserver keyserver.ubuntu.com --recv-keys \"$key\" ;   done   && curl -fsSLO --compressed \"https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz\"   && curl -fsSLO --compressed \"https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc\"   && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz   && gpgconf --kill all   && rm -rf \"$GNUPGHOME\"   && mkdir -p /opt   && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/   && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn   && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg   && rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz   && apt-mark auto '.*' > /dev/null   && { [ -z \"$savedAptMark\" ] || apt-mark manual $savedAptMark > /dev/null; }   && find /usr/local -type f -executable -exec ldd '{}' ';'     | awk '/=>/ { so = $(NF-1); if (index(so, \"/usr/local/\") == 1) { next }; gsub(\"^/(usr/)?\", \"\", so); print so }'     | sort -u     | xargs -r dpkg-query --search     | cut -d: -f1     | sort -u     | xargs -r apt-mark manual   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false   && yarn --version"
        },
        {
            "created": "2024-02-15T22:56:28.460703629Z",
            "created_by": "/bin/sh -c #(nop) COPY file:4d192565a7220e135cab6c77fbc1c73211b69f3d9fb37e62857b2c6eb9363d51 in /usr/local/bin/ "
        },
        {
            "created": "2024-02-15T22:56:28.550374283Z",
            "created_by": "/bin/sh -c #(nop)  ENTRYPOINT [\"docker-entrypoint.sh\"]",
            "empty_layer": true
        },
        {
            "created": "2024-02-15T22:56:28.643445116Z",
            "created_by": "/bin/sh -c #(nop)  CMD [\"node\"]",
            "empty_layer": true
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-02-16T13:12:19.682953758Z",
            "created_by": "ENV NODE_ENV=production",
            "empty_layer": true
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-02-16T13:12:19.682953758Z",
            "created_by": "RUN /bin/sh -c apt-get update && apt-get install -y openssl # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-02-16T13:12:19.682953758Z",
            "created_by": "ENV PORT=8080",
            "empty_layer": true
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-02-16T13:12:19.682953758Z",
            "created_by": "ENV NODE_ENV=production",
            "empty_layer": true
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-02-16T13:12:19.696048897Z",
            "created_by": "WORKDIR /myapp"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-07T12:48:23.889504789Z",
            "created_by": "COPY /myapp/node_modules /myapp/node_modules # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-07T12:48:25.671360823Z",
            "created_by": "COPY /myapp/node_modules/.prisma /myapp/node_modules/.prisma # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.22239811Z",
            "created_by": "COPY /myapp/build /myapp/build # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.297244208Z",
            "created_by": "COPY /myapp/public /myapp/public # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.30924065Z",
            "created_by": "COPY /myapp/package.json /myapp/package.json # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.323502749Z",
            "created_by": "COPY /myapp/start.sh /myapp/start.sh # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.380748449Z",
            "created_by": "RUN /bin/sh -c chmod +x /myapp/start.sh # buildkit"
        },
        {
            "comment": "buildkit.dockerfile.v0",
            "created": "2024-03-09T16:33:39.380748449Z",
            "created_by": "ENTRYPOINT [\"./start.sh\"]",
            "empty_layer": true
        }
    ],
    "os": "linux",
    "rootfs": {
        "diff_ids": [
            "sha256:ceb365432eec83dafc777cac5ee87737b093095035c89dd2eae01970c57b1d15",
            "sha256:b1cf80d308ef1da5ab832789c3eb6394f0829deba8e059fb35347feb483bf52e",
            "sha256:824d93777a5c92bc1b928b3c703b780a9f2c33f6ae820b20d2c7f135269b6a07",
            "sha256:b56c14caa7701d4a20569426e25f65b3b95ae7cf30a7743e4b11cc23e35d760b",
            "sha256:dda59a3b651ddd478847319a72927f50625e389dedc018bdac2cf00ac4e2e02d",
            "sha256:1c95cfe980de0bc0eed6c23db1bba6501d4451c09905433924fc70b040fd99fa",
            "sha256:7833a8a7ae01ea5430ac72554dac062cf2726584a5c60146d404927b6f71fea9",
            "sha256:96a97975109d85618f8e00de4a63f76f524e82ebf308c6fc9deb170c17733808",
            "sha256:7ef4cd8799d7da43d4423b8e2d0893f0e170f3a97e68c2c81a5f425fa555f891",
            "sha256:1fe7347753ce3c781c9873529b635286ca87e263cd05ad16136b4cf3d271bc66",
            "sha256:568c436c120689aa91f4cccd4d2f2356b09c9c26e00247d5a4182c7a7a53b842",
            "sha256:5d230361e9ee174139b0b778e80201a322e9d5474f52e8701d958fa7b1a5eaa5",
            "sha256:dbd9e6166c565254ad60ee69f917b872549d5bf114c00ae700d760800c6a3e9c",
            "sha256:42cd9eb2b7a23630cd5fbd514c3cbeac8de52d00200f2ffd11a70a12df939a65"
        ],
        "type": "layers"
    }
}
```

**Comment by anatolinicolae** [comment]
No idea on how `udocker` handles env vars in that case, and it's out of scope for Shelf's Docker support. What I can suggest is to either try running a rootless container via [podman](https://podman.io/) (since that's a drop-in replacement) or to dig deeper into `udocker`'s internals to learn how to properly pass env vars if you wanna stick with that...

**Comment by whoamiafterall** [comment]
Okay, thank you for your help and sorry for bothering. 
I tested it on my localhost and it works fine with the exact same ENV Vars, so i guess we can close this one.

**Comment by anatolinicolae** [comment]
I think I figured out your issue: you're passing arguments on the wrong side, after the container name, which passes them to the process instead of udocker.

```bash
# ❌ This is basically ./start.sh --env-file=~/.env-file --publish=3000:8080
udocker run shelf --env-file=~/.env-file --publish=3000:8080

# ✅ This properly sets env vars in udocker
udocker run --env-file=~/.env-file --publish=3000:8080 shelf
```
